name: healthu
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # ——— Fuentes ———
  google_fonts: ^5.0.0

  # ——— Internacionalización ———
  intl: ^0.18.0

  # ——— Gráficas (versión moderna con parámetros nombrados) ———
  fl_chart: ^0.65.0       # ← subido

  # ——— Otros ———
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# ───── Elimina por completo el bloque dependency_overrides ─────
